### ISSUE TITLE
Missing wordlist for Northern Sami

### ISSUE THREAD

**Issue by omarandlorraine** [hisbaan/wordlists#2]
There is currently no wordlist for Northern Sami (ISO code se or sme). Ot would be great if didyoumean could support this language. 

Giellatekno may have the file we need.

**Comment by hisbaan** [comment]
I did some exploring of Giallatekno (via lots of google translate), but the actual downloads for the dictionary files are giving me a 404. I'll try and look for it from other sources

**Comment by hisbaan** [comment]
I was able to find a Finnish to Northern Sami translation file. It only contains about eleven thousand words but I wasn't able to find much better so I hope that this helps. I'll wait for your approval before I merge the PR. It is #3

**Comment by omarandlorraine** [comment]
Brilliant, the encoding is good and seems to have most common words
